### PR TITLE
info_prashant

### PR DESCRIPTION
**Pull request by coakleyprashant**

### CODE REVIEW

**Comment by openp2pdesign** [comment]
You should not edit the README.md file. Instead, you should create a new file with your name and surname details (name.surname.md) and put your bio there. try again, commit, sync, and create another pull request

**Comment by Tessaberg** [comment]
Sounds good!

**Comment by coakleyprashant** [comment]
new files added, please check.

**Comment by openp2pdesign** [comment]
Done!

**Pull request closed without merging**
